kafka:
  broker: localhost:9092
  zookeeper: localhost:2181
  topic: switchbox
  messageKey: swichbox.key
  
mqtt:
  username: admin
  password: password
  url: tcp://localhost:61613
  autostartup: true
  topic: switchbox
  qos: 1
  inboundclientid: switchbox-mqtt-listener
  outboundclientid: switchbox-mqtt-publisher
  
threadpool:
  core-pool-size: 50
  max-pool-size: 200
  queue-capacity: 50
  
monitor:
  url: http://admin:password@localhost:61680/api/json/broker/connectors/tcp
  interval: 2000
  connected: 0
